name: rankinlab
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - ipywidgets
  - tqdm
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - scipy
  - streamlit
  - plotly
  - requests
  - sqlalchemy
  - psycopg
  - pydantic
  - pip:
      - kaleido
      - psycopg-binary
      - ipyfilechooser
