name: rankinlab
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - ipywidgets
  - tqdm
  - seaborn
  - numpy
  - scipy
  - plotly
  - requests
  - sqlalchemy
  - psycopg
  - pydantic
  - pip:
      - kaleido
      - psycopg-binary
      - ipyfilechooser
      - altair==4.0
      - protobuf==3.20
      - matplotlib
      - pandas
      - streamlit
